### ISSUE TITLE
AABB names

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#302]
- [x] `func_72321_a`: `addCoord` -> `expand`
- [x] `func_72314_b`: `expand` -> `grow`
- [x] `func_186662_g`: `expandXyz` -> `grow`
- [x] `func_186664_h`: `contract` -> `shrink`
- [ ] `func_186666_e`: `setMaxY` -> `withMaxY`
- [x] `func_72326_a`: `intersectsWith` -> `intersects`
- [x] `func_72318_a`: `isVecInside` -> `contains`
- [ ] `func_72320_b`: `getAverageEdgeLength` -> `getSize`

Comments welcome.

**Comment by kenzierocks** [comment]
Agree with all except `getAverageEdgeLength` -- that name seems to be fitting.

**Comment by The-Fireplace** [comment]
Why not change addCoord to addValuesToCoord? It makes it have a clearer difference than grow and expand do, while also making the meaning more clear.

**Comment by gigaherz** [comment]
Hmm, I like `expand`, `contract` and `intersectsWith` more than the suggested new names. Those are the names used in technical areas when working with AABBs, at least so far as I have experienced them.

My choices would be:
    func_186666_e: `setMaxY` -> `withMaxY`
    func_72321_a: `addCoord` -> `union` or maybe `include` (not satisfied)
    func_72314_b: `expand` -- KEEP
    func_186662_g: `expandXyz` -> `expand`
    func_72326_a: `intersectsWith` -- KEEP
    func_72318_a: `isVecInside` -> `contains`
    func_72320_b: `getAverageEdgeLength` -- KEEP (for lack of a better choice, because it is NOT the "size" at all and the suggested name would be extremely confusing)
    func_186664_h: `contract` -- KEEP

**Comment by covers1624** [comment]
+1 on @gigaherz suggestion.
 `include` feels more natural for `func_72321_a`

**Comment by kashike** [comment]
done.
- [x] `func_72314_b`: `expand` -> `grow`
- [x] `func_186662_g`: `expandXyz` -> `grow`
- [x] `func_186664_h`: `contract` -> `shrink`
- [x] `func_72321_a`: `addCoord` -> `expand`
- [x] `func_72326_a`: `intersectsWith` -> `intersects`
- [x] `func_72318_a`: `isVecInside` -> `contains`
- [x] `func_191194_a`: `move` -> `offset`

**Comment by ThisTestUser** [comment]
I think the comments for the above functions are still incorrectly mapped. For example, one comment links to addCoord, which doesn't exist anymore.

**Comment by williewillus** [comment]
Comments are open to modification for anyone, so you can go in and fix it yourself (just sm to the same name but give a different comment)

**Comment by williewillus** [comment]
Just dropping a comment in here for posterity.

Some of the renames here were well-intentioned but have caused many, many, many hidden bugs in mods because an existing name was remapped to another existing name with the same signature, but different semantics. 

This means bugs are introduced into every mod that upgraded past this mapping change, *without a compilation error* or any other signal that something is wrong. My example is `expand` -> `grow`, which has caused hidden problems in all three of the mods I'm actively involved in. Many more probably lurk undiscovered in newly ported mods.

In the future, we should probably think thrice and ensure something like this doesn't happen again

**Comment by xrnss** [comment]
I know this was years ago but having the issue with expand/grow. The mapping says func_72314_b should be grow, but Forge believes grow doesn't exist, so I'm using expand. Hopefully that'll work
