### ISSUE TITLE
Rename stronghold-specific worldgen names to more general names

### ISSUE THREAD

**Issue by mezz** [ModCoderPack/MCPBot-Issues#416]
These mappings are used for all kinds of worldgen structures, not just strongholds.

`func_180513_a` : `getStrongholdGen` -> `getNearestStructurePos`
`func_180706_b` : `getClosestStrongholdPos` -> `getNearestStructurePos`

This makes them similar to the mapping for `World.func_190528_a` (`findNearestStructure`) which calls these.

**Comment by kashike** [comment]
done.
- [x] `func_180513_a`: `getStrongholdGen` -> `getNearestStructurePos`
- [x] `func_180706_b`: `getClosestStrongholdPos` -> `getNearestStructurePos`

**Comment by NeunEinser** [comment]
They are still not updated in mcp_snapshot-20171015-1.12.zip.

**Comment by Pokechu22** [comment]
They look correct for me in MCPBot, and my older downloaded CSVs.

**Comment by NeunEinser** [comment]
Hmm, weird I downloaded today's snapshot-mappings and in there it seems to be fine. Maybe there was just something wrong in the 20171015 snapshot.
