### ISSUE TITLE
Build Failed With snapshot-20200526-1.15.1

### ISSUE THREAD

**Issue by Andy-K-Sparklight** [ModCoderPack/MCPBot-Issues#878]

**Comment by Andy-K-Sparklight** [comment]
I got a error build\tmp\expandedArchives\forge-1.15.2-31.2.0_mapped_snapshot_20200526-1.15.1-sources.jar_25b1ab4809e1e452063741392e51b956\net\minecraft\client\audio\AudioStreamBuffer.java:17: ����: ������ AudioStreamBuffer�ж����˱��� buffer
   private int buffer;

**Comment by ichttt** [comment]
My bad, somehow it let me name a var `buffer` even though it was already defined in that scope. I changed to name of the one buffer. Should be fixed in the next snapshot (`20200528-1.15.1`)

**Comment by Andy-K-Sparklight** [comment]
Emm……still failed in today's snapshot
build\tmp\expandedArchives\forge-1.15.2-31.2.0_mapped_snapshot_20200527-1.15.1-sources.jar_d36496b67ebb7a3c301a75a40bf38a7b\net\minecraft\client\audio\AudioStreamBuffer.java:17: ����: ������ AudioStreamBuffer�ж����˱��� buffer
   private int buffer;
               ^

I was wondering: Do you mean in 20200528-1.15.1  ?

**Comment by Andy-K-Sparklight** [comment]
Oh okay
